name: 'resourceful-tako'

services:
  resourceful_tako:
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - 7061:7060
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './resourceful-tako/logs:/logs'
      - './resourceful-tako/config:/config'
    environment:
      NODE_ENV: production
      DATABASE_URL: 'file:/config/dev.db'
      API_KEY: '<generate_a_long_api_key>'
