name: 'Create release'
on:
  release:
    types:
      - 'published'

jobs:
  publish_to_container_registry:
    name: 'Publish to container registry'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Login to private Docker registry'
        uses: 'docker/login-action@v3'
        with:
          registry: 'ghcr.io'
          username: '${{ secrets.CR_USERNAME }}'
          password: '${{ secrets.CR_PAT }}'
      - name: 'Build and push'
        uses: 'docker/build-push-action@v5'
        with:
          push: true
          context: '.'
          file: './docker/prod/Dockerfile'
          labels:
            - 'org.opencontainers.image.source="https://github.com/${{ github.repository }}"'
          tags:
            - 'github.com/${{ github.repository }}:latest'
          build-args: |
            RELEASE_COMMIT='${{ github.sha }}'
